server:
  port: 81
  servlet:
    session:
      timeout: 600
  max-http-header-size: 8192
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/plain,text/xml,text/html,application/json,application/xml

spring:
  application:
    name: dome03_merchant
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  aop:
    proxy-target-class: true
  jmx:
    default-domain: ${spring.application.name}

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wfx?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    druid:
      initial-size: 20
      min-idle: 100
      max-active: 500
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 20
      validation-query-timeout: 30000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      max-open-prepared-statements: 50
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
#  redis:
#    host: localhost
#    port: 6379
#    password :
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.chenlong.entity.dto
  configuration:
    map-underscore-to-camel-case: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
